name: Build Value Testing
on: [pull_request]

jobs:
 windows_test:
    name: Execute Tests on Ubuntu
    runs-on: windows-latest
    steps:
      - name: 'Checkout the repository'
        uses: actions/checkout@v2
      - name: 'Building web application to be tested'
        run: npm install
      - run: npm run wdio-BVT
